### ISSUE TITLE
Update labels design guideline page with updated visuals

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#2411] opened 2021-03-16 19:57 UTC
https://www.patternfly.org/v4/components/label/

React / HTML are correct - design guidelines page is outdated.

@maryshak1996

**Comment by mmenestr** [comment] 2021-05-03 15:51
Closing because duplicate of this one https://github.com/patternfly/patternfly-org/issues/2382

**Closed by mmenestr** 2021-05-03 15:51 UTC
Labels: PF4 Design, PF4 design Guidelines
