### ISSUE TITLE
Add design snippets to remaining layouts and components

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#1132] opened 2019-05-21 17:42 UTC
It would helpful to add the docs section since it includes valuable info, e.g. media query info.

**Comment by ncameronbritt** [comment] 2019-05-21 18:14
For the layout pages in particular, I also think that the Overview portion of the documentation could be improved with use cases. For example, if one of the reasons for the Split layout is to format list rows, that'd be a useful thing to see documented. The skeletal examples on the pages don't always help illustrate why one should employ a given layout.

**Comment by redallen** [comment] 2019-12-17 17:25
Are you asking for what I call "design snippets" at the top of layout pages like this?
![image](https://user-images.githubusercontent.com/47335686/71019437-4c11bb80-20c8-11ea-9aad-56b61171a888.png)

We can easily add these.

cc @mcarrano

**Comment by matthewcarleton** [comment] 2019-12-17 17:39
I'm talking about the "documentation" section we have in the html components. @ncameronbritt might be referring to improving the content rather than just aligning both versions (html, react)

**Comment by ncameronbritt** [comment] 2019-12-17 18:30
Hard to remember what I was talking about 7 months ago...

If I look at Components pages, I see some description right at the top of the page for both React and HTML components. Awesome! 

If I look at Layouts pages, Bullseye for example, I see Overview in the Documentation section which provides a little summary of what the thing is. On the React version I do not see that. 

Can we update these Layout pages to be similar to the Components pages?  I.e. include the design snippet on the React pages and move it to the top on both React and HTML versions?

**Comment by redallen** [comment] 2019-12-17 20:17
Yeah, the inconsistency is caused by HTML tending to have better docs than React. Some HTML components have an "Overview" section that can more or less be the design snippet. Sometimes the overview goes really in depth, though like [for Check.](https://www.patternfly.org/v4/documentation/core/components/check)

I'll change this issue to adding design snippets to layouts and components currently missing them.

**Comment by mcarrano** [comment] 2020-01-08 00:30
This is a duplicate of https://github.com/patternfly/patternfly-org/issues/1489 Will close.

**Closed by mcarrano** 2020-01-08 00:30 UTC
Labels: PF4 website issue, duplicate
