### ISSUE TITLE
property table is just not wide enough to handle values consistantly 

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-org#1652] opened 2020-01-29 20:00 UTC
The issue is that the values in the properties tables are unreadable and need to not wrap. The side effect of this is that we are not allowing the table enough width to grow with some of the values. 

**Example:**
![Screen Shot 2020-01-29 at 2 58 31 PM](https://user-images.githubusercontent.com/57504257/73392485-ed835400-42a7-11ea-8b60-636d5fe089f2.png)

**Comment by rachael-phillips** [comment] 2020-01-29 20:43
Here this is in action on the FormSelect component  - how the code lives in the table. Maybe we could reconsider formatting this altogether?

<img width="1546" alt="Screen Shot 2020-01-29 at 3 41 17 PM" src="https://user-images.githubusercontent.com/40275806/73395687-02fb7c80-42ae-11ea-8e09-cffd8d73d2c4.png">

cc @mcarrano for your awareness

**Comment by redallen** [comment] 2020-01-31 16:19
Duplicate of #1560 , let's move discussion there.

For the record @rachael-phillips , CSS Variable tables are rendered and styled differently that our other tables and I believe are unrelated to @ddonahue007 's changes.

**Closed by redallen** 2020-01-31 16:19 UTC
Labels: docs, infrastructure
