### ISSUE TITLE
Text/icons are bunched together on List View code panel 

### ISSUE THREAD

**Issue by michael-coker** [patternfly/patternfly-org#512] opened 2018-01-24 21:08 UTC
URL with display issue, under "Row Variation #5"
* http://www.patternfly.org/pattern-library/content-views/list-view/#/code

I'm not seeing that issue in the test page
* https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-rows.html

**Comment by mcarrano** [comment] 2018-01-24 21:48
Yeah, I've been kinda aware of this one but not sure what to do about it. The problem is that the examples are too wide to fit in this fixed width page, but not sure why the responsive behavior here is not to wrap. If you reduce the width of the test page, do you see the same effect @michael-coker ? Is this really a coding bug with the example?

**Comment by michpetrov** [comment] 2018-01-25 12:01
(Duplicate of #505)

@mcarrano the issue is caused by the JS script that tries to equalize the width of the items. Since this example is placed in a tab that's initially hidden the width is set to 0. (I tried replacing the script with CSS flex rules and it works well but it's a substantial change.)

**Comment by mcarrano** [comment] 2018-01-25 15:17
If there is not a simple fix for this, my recommendation is to remove the example. It's not that useful.

Thoughts @LHinson @amarie401 @cliffpyles ?

**Comment by michael-coker** [comment] 2018-01-25 15:21
@michpetrov a potential simple fix for just that page would be to wrap the equal width column JS in `$(window).on('load',{})` instead of `$(document).ready({})`. Would that work?

**Comment by michpetrov** [comment] 2018-01-26 10:38
@michael-coker if the script is to be executed it has to happen after the example becomes visible, i.e. after you switch to the code tab

**Comment by dabeng** [comment] 2018-01-30 11:38
Hi @mcarrano @michpetrov  @michael-coker , I think the following code snippets of patternfly repo cause this issue:
patternfly/tests/pages/_includes/widgets/list-view/list-view-variation-5.html
```js
  $(document).ready(function () { // line 113
  	var widest = 0;
  	$('.list-view-pf-equalized-column .list-view-pf-additional-info-item').each( function() {
  		widest = $(this).width() > widest ? $(this).width() : widest;
  	}).width(widest);
  });
```
We know that jquery can only return "0"  when you want to get width or height from a hidden element. 

Here's my preliminary solution and **[Demo](https://rawgit.com/dabeng/patternfly-org/list-view-dist/_site/pattern-library/content-views/list-view/)** page:
```js
  $(document).ready(function () { // line 113
    $('#tabs-pattern').one('shown.bs.tab', 'a[data-toggle="tab"]', function (e) {
      var widest = 0;
      $('.list-view-pf-equalized-column .list-view-pf-additional-info-item').each( function() {
        widest = $(this).width() > widest ? $(this).width() : widest;
      }).width(widest);
    });
  });
```

Simply, I append eventHandler for "shown.bs.tab" event in order to get actual width of "div.list-view-pf-additional-info-item"

**Comment by dabeng** [comment] 2018-05-17 05:58
This issue doesn't exist on current patternfly.org site.

<img width="1117" alt="screen shot 2018-05-17 at 1 56 08 pm" src="https://user-images.githubusercontent.com/5689075/40159104-4b0d5d90-59da-11e8-8876-69600fc3108c.png">

**Closed by dabeng** 2018-05-17 05:58 UTC
