### ISSUE TITLE
Add description of advanced proptypes

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-org#1539] opened 2019-11-12 15:17 UTC
Hi,

Page: https://www.patternfly.org/v4/documentation/react/components/table#props

There are propTypes like `IRow`, `IExtraRowData`, etc. but as a reader I have no idea what it is. It would be nice to have these types documented.

**Comment by rachael-phillips** [comment] 2019-11-12 22:25
@redallen is this something we should fix upstream or can this be fixed on the website?

**Comment by redallen** [comment] 2019-11-14 16:18
This is a multi-faceted issue. This can be fixed by allowing us to specify our own types that appear in the documentation so we can exclude the Typescript props. Duplicate of https://github.com/patternfly/patternfly-react/issues/2139 .

**Closed by redallen** 2019-11-14 16:18 UTC
