### ISSUE TITLE
Font missing from release notes page

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1877] opened 2020-06-09 20:52 UTC
See screenshot.
The font in the release links is serif, everything else is sans-serif. I'm thinking this wasn't intentional?

![image](https://user-images.githubusercontent.com/23172038/84198439-8f465900-aa71-11ea-9088-429f600ef44e.png)

**Comment by evwilkin** [comment] 2020-06-11 17:09
@rachael-phillips @katierik thanks for getting this issue up - I've got a [PR up to fix this](#1853 ), related to some issues logged by other folks as well, if you don't mind taking a look.

@rachael-phillips your screenshots above mention Typography & Training, but it looks like the Training screenshot is just a duplicate of Typography.  I don't see anything on the Training section, but if you don't mind double checking that there's not something I'm missing that would be great!

**Closed** 2020-06-11 17:34 UTC
Labels: bug, infrastructure
