### ISSUE TITLE
Bug - documentation-framework extended interface/type alias properties are not parsed and displayed

### ISSUE THREAD

**Issue by jpuzz0** [patternfly/patternfly-org#3423] opened 2023-02-22 16:49 UTC
**Describe the problem**
When attempting to display component props or some other type within the `Props` section of a component's documentation page, and the interface/type alias used extends or joins with another interface/type alias, those members are not parsed and displayed unless they're explicitly written.

Example:
```
interface ComponentBProps {
  propThree: string[];
  propFour: number[];
}

interface ComponentAProps extends ComponentBProps {
  propOne: string;
  propTwo: number;
}
```

**Actual behavior**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/96431149/220697636-16976116-9f52-4c34-8fa6-293d7344aa87.png">

**Expected behavior**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/96431149/220698264-3ccc34bd-5afa-41f3-ba5e-d80e04ef6dcf.png">

**Any other information?**
Setting a type alias equal to another type (enum, interface, other type alias) also isn't accounted for. This will get complicated fast if type utilities are involved. e.g.
```
type SomeType = Omit<Pick<SomeOtherType, 'pickedProp'>, 'omittedPropOne' | 'omittedPropTwo'>
```
The dilemma here is that we have certain capabilities available to us syntactically in our code revolving around types that the documentation-framework is not currently capable of handling.

**Comment by nicolethoen** [comment] 2024-12-03 19:18
Closing as a duplicate of #3579

**Closed by nicolethoen** 2024-12-03 19:18 UTC
