### ISSUE TITLE
Redesign: Change homepage background color from white

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2023] opened 2020-08-10 14:46 UTC
See related design issue: https://github.com/patternfly/patternfly-design/issues/894

On the homepage on PatternFly.org for the new site redesign, change the white body of the "Hello we're PatternFly" section to the grey used on other body pages. It's #FAFAFA on the colors page. patternfly.org/v4/design-guidelines/styles/colors

**Comment by redallen** [comment] 2020-08-19 19:30
Duplicate of #2040

**Closed by redallen** 2020-08-19 19:30 UTC
