### ISSUE TITLE
Home page "shimmy" when typing into the search field on Chrome or MS Edge browsers

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2370] opened 2021-01-26 17:02 UTC
When typing into the search field in the header of the masthead, the display "shimmies" left to right as the vertical scroll bar shows/hides. This effect only appears on Chrome based browsers, not Firefox or Safari.

Found by Matt Reid. Video to be added.

**Comment by mattreid** [comment] 2021-01-26 18:22
From some quick browser testing, this seems to only affect Chromium based browsers (I didn't try it in Brave, but I suspect we'd see the same shimmy). There seems to be something going on between the placement of the search plugin overlay and whatever CSS/styling is happening when mousing over the icons in that area. If you get the cursor in the right spot, it will continuously trigger this behavior. I'm not sure if OS impacts this at all, I'm on a Mac.

It might be related to where we place the overlay, as when that appears, no matter how wide my window is (the videos were taken ~1600px), it adds a horizontal scrollbar to my browser because the search overlay is placed slightly off the active viewport.

I made two quick videos demonstrating this.
https://user-images.githubusercontent.com/1242413/105886626-9dcd8a80-5fd8-11eb-9950-a2490fc955ed.mov

https://user-images.githubusercontent.com/1242413/105886633-9efeb780-5fd8-11eb-974f-4f3f47c2c621.mov

**Comment by mcarrano** [comment] 2021-01-26 18:46
Thanks for posting the additional info @mattreid .

@redallen @evwilkin can you take a look at this?

**Comment by redallen** [comment] 2021-01-26 19:19
I can't reproduce this but I've been thinking of making a custom search for patternfly.org that should work better than Algolia's and not have this problem. Interfacing with both their JS/CSS that ties to the search box as well as their backend that (still) doesn't crawl our content very well has been painful in my experience.

I can pretty quickly put together some JS for it. For example searching "Empty state" could reveal the following 8 pages:
```json
[
  '/components/empty-state/design-guidelines': {
    id: "Empty state",
    title: "Empty state",
    toc: [{"text":"Usage"},{"text":"Elements"},{"text":"Design guidelines"},[{"text":"Icons"},{"text":"Title and body"},{"text":"Primary and secondary buttons"},{"text":"Alignment"},{"text":"Toolbars or filters in empty states"}],{"text":"Use case examples"},[{"text":"First-use or get started"},{"text":"No data to show"},{"text":"Required configuration"},{"text":"User not entitled or does not have access"},{"text":"Back-end failure"},{"text":"Success"},{"text":"Addition or creation"}]],
    section: "components",
    source: "design-guidelines"
  },
    '/components/empty-state/html': {
    id: "Empty state",
    title: "Empty state",
    toc: [{"text":"Examples"},[{"text":"Basic"},{"text":"Extra small"},{"text":"Small"},{"text":"Large"},{"text":"Extra large"},{"text":"With primary element"}],{"text":"Documentation"},[{"text":"Accessibility"},{"text":"Usage"}]],
    examples: ["Basic","Extra small","Small","Large","Extra large","With primary element"],
    section: "components",
    source: "html",
  },
  '/components/table/html-demos': {
    id: "Table",
    title: "Table",
    toc: [{"text":"Demos"},[{"text":"Basic"},{"text":"Sortable"},{"text":"Expandable"},{"text":"Compact"},{"text":"Compound expansion"},{"text":"Loading state demo"},{"text":"Empty state"},{"text":"Static bottom pagination"},{"text":"Column management modal"},{"text":"Sticky header"}]],
    fullscreenExamples: ["Basic","Sortable","Expandable","Compact","Compound expansion","Loading state demo","Empty state","Static bottom pagination","Column management modal","Sticky header"],
    section: "components",
    source: "html-demos",
  },
  '/components/empty-state/react': {
    id: "Empty state",
    title: "Empty state",
    toc: [{"text":"Examples"},[{"text":"Basic"},{"text":"Extra small"},{"text":"Small"},{"text":"Large"},{"text":"Extra large"},{"text":"Spinner"},{"text":"No match found"}]],
    examples: ["Basic","Extra small","Small","Large","Extra large","Spinner","No match found"],
    section: "components",
    source: "react",
  },
    '/components/table/react': {
    id: "Table",
    title: "Table",
    toc: [{"text":"Table examples"},[{"text":"Basic"},{"text":"Row click handler and header cell tooltips/popovers"},{"text":"Custom row wrapper"},{"text":"Sortable & wrapping headers"},{"text":"Selectable"},{"text":"Selectable radio input"},{"text":"Actions and first cell in body rows as th"},{"text":"Expandable"},{"text":"Compound expandable"},{"text":"With width and breakpoint visibility modifiers"},{"text":"Controlling text"},{"text":"Modifiers with table text"},{"text":"Empty state"},{"text":"Editable rows"},{"text":"Favoritable"}],{"text":"TableComposable examples"},[{"text":"Composable: Basic"},{"text":"Composable: Row click handler, custom row wrapper, header tooltips & popovers"},{"text":"Composable: Sortable & wrapping headers"},{"text":"Composable: Selectable"},{"text":"Composable: Selectable radio input"},{"text":"Composable: Actions"},{"text":"Composable: Expandable"},{"text":"Composable: Compound expandable"},{"text":"Composable: Cell width, breakpoint modifiers"},{"text":"Composable: Controlling text"},{"text":"Composable: Modifiers with table text"},{"text":"Composable: Favoritable"}]],
    examples: ["Basic","Row click handler and header cell tooltips/popovers","Custom row wrapper","Sortable & wrapping headers","Selectable","Selectable radio input","Actions and first cell in body rows as th","Expandable","Compound expandable","With width and breakpoint visibility modifiers","Controlling text","Modifiers with table text","Empty state","Editable rows","Favoritable","Composable: Basic","Composable: Row click handler, custom row wrapper, header tooltips & popovers","Composable: Sortable & wrapping headers","Composable: Selectable","Composable: Selectable radio input","Composable: Actions","Composable: Expandable","Composable: Compound expandable","Composable: Cell width, breakpoint modifiers","Composable: Controlling text","Composable: Modifiers with table text","Composable: Favoritable"],
    section: "components",
    source: "react",
  },
  '/components/table/react-demos': {
    id: "Table",
    title: "Table",
    toc: [[{"text":"Bulk select"},{"text":"Expand/collapse all"},{"text":"Column management"},{"text":"Filterable"},{"text":"Automatic pagination"},{"text":"Pagination"},{"text":"Sticky header"}],{"text":"Empty states"},[{"text":"Empty"},{"text":"Loading"},{"text":"Error"}]],
    examples: ["Bulk select","Expand/collapse all","Column management","Filterable","Automatic pagination","Pagination","Empty","Loading","Error"],
    fullscreenExamples: ["Sticky header"],
    section: "components",
    source: "react-demos",
  },
  '/developer-resources/upgrade-guide/html': {
    id: "Upgrade guide",
    title: "Upgrade guide",
    toc: [{"text":"Global"},[{"text":"Colors"},{"text":"Mobile first CSS"},{"text":"Vertical navigation hidden breakpoint"},{"text":"Removed \"shield\" CSS"},{"text":"Default font"},{"text":"Directory structure"},{"text":"Code changes"}],{"text":"Components"},[{"text":"About modal box"},{"text":"Accordion"},{"text":"Alert"},{"text":"Application launcher"},{"text":"Backdrop"},{"text":"Breadcrumb"},{"text":"Button"},{"text":"Card"},{"text":"Chip"},{"text":"Chip group"},{"text":"Clipboard copy"},{"text":"Content"},{"text":"Context selector"},{"text":"Data list"},{"text":"Drawer"},{"text":"Dropdown"},{"text":"Empty state"},{"text":"Expandable section (previously Expandable)"},{"text":"File upload"},{"text":"Form"},{"text":"Form control"},{"text":"Input group"},{"text":"Label"},{"text":"Login"},{"text":"Modal box"},{"text":"Nav"},{"text":"Notification drawer"},{"text":"Options menu"},{"text":"Page"},{"text":"Pagination"},{"text":"Popover"},{"text":"Radio"},{"text":"Select"},{"text":"Simple list"},{"text":"Skip to content"},{"text":"Switch"},{"text":"Tabs"},{"text":"Table"},{"text":"Toolbar (previously Data toolbar)"},{"text":"Tooltip"},{"text":"Wizard"}],{"text":"Layouts"}],
    section: "developer-resources",
    source: "html",
  },
  '/developer-resources/upgrade-guide/react': {
    id: "Upgrade guide",
    title: "Upgrade guide",
    toc: [{"text":"Global"},{"text":"React core"},[{"text":"About modal"},{"text":"Accordion"},{"text":"Alert"},{"text":"Application launcher"},{"text":"Background image"},{"text":"Button"},{"text":"Card"},{"text":"Chip group"},{"text":"Context selector"},{"text":"Data list"},{"text":"Divider"},{"text":"Drawer"},{"text":"Dropdown"},{"text":"Empty state"},{"text":"Expandable section (formerly Expandable)"},{"text":"Flex"},{"text":"Form select"},{"text":"Gallery"},{"text":"Grid"},{"text":"Label"},{"text":"Level"},{"text":"Login page"},{"text":"Modal"},{"text":"Nav"},{"text":"Options menu"},{"text":"Page"},{"text":"Pagination"},{"text":"Popover"},{"text":"Progress"},{"text":"Select"},{"text":"Skip to content"},{"text":"Split"},{"text":"Stack"},{"text":"Tabs"},{"text":"Table"},{"text":"Text input"},{"text":"Text area"},{"text":"Title"},{"text":"Toolbar (formerly DataToolbar)"},{"text":"Wizard"}],{"text":"React charts"},{"text":"React icons"},{"text":"React inline edit extension"},{"text":"React styles"},{"text":"React tokens"}],
    section: "developer-resources",
    source: "react",
  }
]
```

@mcarrano Could you come up with a design to show this information? @jschuler and I looked through the Algolia statistics and most consumers are searching for components, so I imagine we'd want to group `/components/empty-state/*` together and then show "Design guidelines", "HTML", and "React". But I don't know if they search a TOC item how we'd want to show it. For example searching "Basic" might reveal 100+ "Basic" examples. Algolia handles this by just showing the top N items.

**Comment by mcarrano** [comment] 2021-01-26 21:02
@redallen @evwilkin I can open a design issue for this. Should I assume that we want a similar approach with the search results displaying in a panel that drops from the search field?

@rachael-phillips Had we previously done any custom designs for the PF website search? If so we might be able to reference those.

**Comment by redallen** [comment] 2021-01-26 21:40
@mcarrano That's right, this would still be a panel that drops down from the search field. I'm open to showing the `section`, `source`, or `toc` items inside there however you see fit. Just be aware a custom implementation can only search text that appears in the `title` of the page or its TOC.

**Comment by evwilkin** [comment] 2021-02-03 20:13
@mcarrano PR #2378 was merged which fixes the original issue here - when a design issue is created for building a new search lets close this out & set up a new React issue referencing this so we don't lose track of the notes above.

**Comment by redallen** [comment] 2021-05-26 19:10
Closing since original issue was solved. We can open a new issue for a custom search.

**Closed by redallen** 2021-05-26 19:10 UTC
