### ISSUE TITLE
Review commented out global styles in typography.js

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4075] opened 2024-06-04 13:46 UTC
In the above referenced file there are several references to removed global style values which are currently commented out.

These style should be reviewed and removed if they're no longer needed, or updated to use a token if they are needed.

**Comment by nicolethoen** [comment] 2024-07-10 12:06
Duplicate of #4069

**Closed by nicolethoen** 2024-07-10 12:06 UTC
