### ISSUE TITLE
There is an unexpected space between table toolbar and datatable

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#514] opened 2018-01-25 14:02 UTC
This is being moved from the patternfly core repo seen here [#932](https://github.com/patternfly/patternfly/issues/932)

**Comment by dabeng** [comment] 2018-01-27 04:14
Hi @matthewcarleton @mcarrano .The issue is cased by the following css snippets of pattern-site.css.
```css
.example-pf .blank-slate-pf,.example-pf .dataTables_wrapper,.example-pf .progress,.example-pf .toolbar-pf {
    margin-bottom: 10px
}
```

**Comment by matthewcarleton** [comment] 2018-01-27 15:12
@dabeng thanks, ya I saw this. Without investigating too deeply I didn't see the reason for this being added. I think it's likely added without the consideration of how .example-pf .toolbar-pf can affect more than just the desired toolbar.

**Comment by dabeng** [comment] 2018-01-28 00:50
@matthewcarleton , you are right. The table view is composed of toolbar-pf and dataTables_wrapper. The above setting applies only to single toolbar-pf or dataTables_wrapper.

**Comment by matthewcarleton** [comment] 2018-01-29 13:19
@dabeng can you investigate this further and track down where that margin is needed? I'm assuming if we just remove it something will not look good.

**Comment by dabeng** [comment] 2018-01-30 05:40
Hi @matthewcarleton . I'm glad to fix it. The following is preliminary solution:
source/_includes/code/content-views/table-view/code.md
```md
<div class="example-pf table-view-pf"> // line 4
 {% include widgets/table-view/table-view.html %}
</div>
```

source/_less/patternfly-site.less
```css
.example-pf {
 ...
  &.table-view-pf {  // line 194
    .dataTables_wrapper,
    .toolbar-pf { margin-bottom: 0; }
  }
 ...
}
```
Here‘s the **[demo](https://rawgit.com/dabeng/patternfly-org/dt-space-dist/_site/pattern-library/content-views/table-view/)** page.
@mcarrano @jeff-phillips-18 @jgiardino Do you have any thoughts about this bug-fix ?

**Comment by matthewcarleton** [comment] 2018-01-30 15:00
hey @dabeng thanks for looking into this. A couple questions: why do we need a preliminary solution here? I also wonder if it's better to rewrite the original css to target what needs styling rather than overwrite it with what you have here.

**Comment by dabeng** [comment] 2018-01-31 02:37
Hi @matthewcarleton , thanks for continuous attention 😊. For the sake of coming to an agreement on final solution, I put forward my preliminary solution as reference. As for second question, I apply incremental changes¹ in order to not interfere with current margin-bottom setting². in other words, I provide code 1 setting especially for the combination of toolbar-pf and dataTables_wrapper.
code 1
```css
.example-pf.table-view-pf .dataTables_wrapper, .example-pf.table-view-pf .toolbar-pf {
    margin-bottom: 0;
}
```
code 2
```css
.example-pf .blank-slate-pf, .example-pf .dataTables_wrapper, .example-pf .progress, .example-pf .toolbar-pf {
    margin-bottom: 10px;
}
```

**Comment by jgiardino** [comment] 2018-01-31 14:23
These are styles that only get used in patternfly.org, correct? If so, then there are a limited number of items that have these styles applied. I agree with @matthewcarleton that it would be better to refactor and rewrite the original css, rather than add new css to overwrite the existing css. I think this work would involve: 
1. Finding all the pages/cases where the selectors in question are applied in patternfly.org 
2. Evaluate why `margin-bottom: 10px` is needed in these cases (e.g. is it for pf.org page layout, or to address some issue within the patternfly code sample?) 
3. Update the selectors as needed. 
    - Maybe we use existing classes, or maybe we define a new pf.org utility class. It's hard to say at this point without knowing all the cases where this is used and why. My guess is that it was added to either improve the page layout or to deal with some css conflict, since we're pulling in angular css on these pages too. But it would be great to find a solution that helps clarify the purpose of these selectors.

I'm interested in hearing other thoughts about this approach?

**Comment by mcarrano** [comment] 2018-01-31 15:23
I'd like to bring @amarie401 into this conversation. I'm a bit suspicious because I'm sure this problem only showed up recently and _may_ have resulted from changes made to the code page layout to add the JS repo links.

Amy, is there anything you changed that might have affected this spacing?

**Comment by amarie401** [comment] 2018-01-31 15:40
@mcarrano I don't believe so. I touched the ```margin-bottom``` for the ```.page-tabs-header``` [here](https://github.com/patternfly/patternfly-org/pull/502/files#diff-f64718348a41f7e42a29d507ad8b1e44R1428). I don't recall touching any styling related to tables in my previous PR.

**Comment by matthewcarleton** [comment] 2018-01-31 16:18
Looking at the blame tool this is where it looks like the change came from [here](https://github.com/patternfly/patternfly-org/commit/cee3b92d1754b24a2e042549e03d2cffed55b195) so the css is pretty old. Is it possible the markup changed?

**Comment by amarie401** [comment] 2018-01-31 16:28
@matthewcarleton ahh yes looks like that css has been there for a long time.

**Comment by amarie401** [comment] 2018-02-27 19:57
@dabeng would you be able to work on this issue?

**Comment by dabeng** [comment] 2018-05-23 09:06
Maybe the lightest solution is replace [table view](http://www.patternfly.org/pattern-library/content-views/table-view/#code) wrapper class `.example-pf` with `.pf-example`

@amarie401 I'm interested in hearing your thoughts about this approach.

**Comment by amarie401** [comment] 2018-05-23 18:09
@dabeng that solution appears to work and doesn't require any major css change. Works for me! Could you open up a PR for the solution? Thanks! :)

**Comment by amarie401** [comment] 2018-05-29 21:08
The issue has been fixed and the PR has been merged. I will go ahead and close this.

**Closed by amarie401** 2018-05-29 21:08 UTC
