### ISSUE TITLE
Add ability to reach older version documentation for PF4

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1212] opened 2019-06-04 20:20 UTC
Documentation released that is out of date needs to be publicly accessible - this can be reached using a version switcher, archived somewhere (or in some other way).  Users should be able to quickly identify which version the documentation refers to and view documentation for older releases.

Discussion is needed about whether we do this for major breaking changes (so when @patternfly/patternfly bumps from 2.x to 3.x - do we archive and allow people to switch back to 2.x) and then just update the 3.x visible documentation until we hit 4.x.  We also need to discuss what this means for the @patternfly/react-* packages which can move independently.  A version switcher for those packages could be harder to embed.  We could just bump the switcher for each milestone and only have major breaking milestones once a quarter or on some other cadence.

**Comment by LHinson** [comment] 2019-11-21 18:13
duplicate of #1398

**Closed by LHinson** 2019-11-21 18:13 UTC
Labels: PF4 DEV, infrastructure
