### ISSUE TITLE
Bootstrap-select example broken with v1.13

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-org#555] opened 2018-04-24 16:02 UTC
[Link](http://www.patternfly.org/pattern-library/widgets/#bootstrap-select), it looks like there were some substantial changes done to bootstrap-select and the examples are currently not working. My guess is the plugin might be trying to use Bootstrap 4 styling but I haven't found the root cause.

I have tried to upgrade the version in the main repo but that only resulted in some minor visual changes.

**Comment by dabeng** [comment] 2018-04-25 04:38
@amarie401  I think this issue is caused by the version mismatch between bootstrap-select.js(1.13.1) and bootstrap-select.css(1.12.2) on patternfly.org site.

**Comment by dabeng** [comment] 2018-04-25 04:57
Feel free to play around with https://codepen.io/dabeng/pen/zjBOLO and checkout different version matching. I recommend to set bootstrap-select dependency to ~1.12.2 both on patternfly repo and patternfly-org repo.

**Comment by michpetrov** [comment] 2018-04-25 12:29
@dabeng the issue with the source files - bootstrap-select.js comes from patternfly-org but the .less file comes from patternfly (which is still on 1.12). In 1.13 the button code has changed so the styling is not applied correctly. If we upgrade the main repo the remaining issue seems to be the caret which is slightly misaligned:
![screenshot from 2018-04-25 14-26-22](https://user-images.githubusercontent.com/1999074/39245740-d87d08e4-4894-11e8-8909-c687f4822b49.png)

**Comment by amarie401** [comment] 2018-04-25 18:45
@michpetrov @dabeng looks like pf-org is using `1.12.2` in the package.json but under `_site/components/bootstrap-select/package.json` and the `node_modules/bootstrap-select` it appears to be using `1.13.1`. 

I notice that the context selector on the website is messed up too but 8 days ago when it was merged in there was no issue with it or the bootstrap-selector. Not sure what happened between now and last week. Having trouble pinpointing the reasoning for this since core also uses `1.12.2`.

**Comment by dabeng** [comment] 2018-04-26 03:15
@michpetrov Yes, you are right. bootstrap-select.js(1.13.1) + bootstrap-select.css(1.13.1) works well too - https://codepen.io/dabeng/pen/pVEoeB

**Closed** 2018-04-26 18:44 UTC
