### ISSUE TITLE
Loading bug on AlertGroup page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1565] opened 2019-12-02 21:59 UTC
Browsers: Chrome and Safari

https://www.patternfly.org/v4/documentation/core/components/alertgroup

When clicking on the Alert group page, there is a loading bug on the top right of the page. The interaction happened too quickly to get a screen shot :)

cc @evwilkin and @redallen

**Comment by redallen** [comment] 2020-01-31 15:53
Duplicate of #1660

**Closed by redallen** 2020-01-31 15:53 UTC
Labels: bug, infrastructure
