### ISSUE TITLE
Forms: DO's and DONT's 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#902] opened 2019-04-26 18:28 UTC
In Design Guidelines > usage and Behavior > Forms 

Having the DONT indented seems like a bug rather than a purposeful choice

<img width="852" alt="Screen Shot 2019-04-26 at 2 27 16 PM" src="https://user-images.githubusercontent.com/20118816/56828485-6a703180-682f-11e9-9c2c-334ef8a5fbc0.png">

**Comment by mcarrano** [comment] 2019-04-29 14:29
Duplicate of #966

**Closed by mcarrano** 2019-04-29 14:29 UTC
Labels: CSS, PF4 design Guidelines, PF4 website issue, bug, duplicate, rc.1
