### ISSUE TITLE
Add which version component was added or change was done

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-org#1353] opened 2019-07-18 09:05 UTC
For newer components, or new props with React, there should be an added version to state when it was added. This way you will not run into issues of not knowing whether or not you can use a component or a prop with the version currently installed

For example, if I have v1.51.0 of PF React core I'm not able to use Tabs as it was added in v1.51.1

**Comment by rachael-phillips** [comment] 2019-07-23 13:55
@SpyTec we are currently working on versioning. cc @redallen

**Comment by rachael-phillips** [comment] 2019-08-07 20:13
I'm going to close this issue as this is a duplicate of an effort we are working on in https://github.com/patternfly/patternfly-org/issues/1397

**Closed by rachael-phillips** 2019-08-07 20:13 UTC
